```yaml
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Vérification du projet
    runs-on: self-hosted

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.13.1

      - name: Vérifier les versions
        run: |
          node --version
          npm --version
          test "$(node --version)" = "v24.13.1"
          test "$(npm --version)" = "11.8.0"

```
